FROM oven/bun:1

WORKDIR /app

ENV NODE_ENV=production
ENV BUN_INSTALL_CACHE_DIR=/bun-cache

COPY package.json bun.lock tsconfig.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
COPY deploy ./deploy

RUN bun install --frozen-lockfile
